  - name: debug vars
    ansible.builtin.debug:
      msg: 
      - "{{ cpu }}"
      - "{{ memory }}"
      - "{{ disk }}"
      - "{{ vlan }}"
      - "{{ id }}"
      - "{{ node_name }}"
      - "{{  inventory_hostname }}"
      - "{{ vlan }}{{ id }}"

  - name: Create a full clone of template 9999
    community.general.proxmox_kvm:
      node: "{{ node_name }}"
      api_user: "{{ user }}"
      api_password: "{{ password }}"
      api_host: "{{ node_name }}"
      clone: template
      vmid: 9999
      newid: "{{ vlan }}{{ id }}"
      name: "{{ inventory_hostname }}"
      storage: "{{ storage }}"
      format: "{{ format }}"
      timeout: 120

  - name: modify vm to specified specs 
    community.general.proxmox_kvm:
      node: "{{ node_name }}"
      api_user: "{{ user }}"
      api_password: "{{ password }}"
      api_host: "{{ node_name }}"
      vmid: "{{ vlan }}{{ id }}"
      cores: "{{ cpu }}"
      memory: "{{ memory }}"
      ipconfig: 
        ipconfig0: "ip={{ subnet }}.{{ vlan }}.{{ id }}/{{ cidr }},gw={{ subnet }}.{{ vlan }}.{{ gateway }}"
      update: true 

  - name: set vlan tag on net_0
    community.general.proxmox_nic:
      api_user: "{{ user }}"
      api_password: "{{ password }}"
      api_host: "{{ node_name }}"
      vmid: "{{ vlan }}{{ id }}"
      interface: net0
      bridge: "{{ bridge }}"
      tag: "{{ vlanTag }}"

  - name: Grow existing disk
    community.general.proxmox_disk:
      api_host: "{{ node_name }}" 
      api_user: "{{ user }}"
      api_password: "{{ password }}"
      vmid: "{{ vlan }}{{ id }}" 
      disk: scsi0
      size: "{{ disk }}G"
      state: resized
 
  - name: start the vm
    community.general.proxmox_kvm:
      node: "{{ inventory_hostname }}"
      api_user: "{{ user }}"
      api_password: "{{ password }}"
      api_host: "{{ inventory_hostname }}"
      vmid: "{{ vlan }}{{ id }}"
      state: started
