- hosts: all 
  become: yes
  gather_facts: yes
  strategy: debug
  vars_files:
   - secrets/vault.yml
  tasks:
    - name: debug ipadr
      ansible.builtin.debug:
        msg: "{{ ipadr }}"

    - name: debug dest_net
      ansible.builtin.debug:
        msg: "{{ dest_net }}"

    - name: check if ip is in destination subnet
      ansible.builtin.set_fact:
        data: "{{ ipadr is ansible.utils.in_network dest_net }}"
    
    - name: debugging data
      ansible.builtin.debug:
        msg: "{{ data }}"

    - import_tasks: tasks/create_vm.yml
      when: data == "true" 
