- hosts: proxmox
  become: yes
  gather_facts: yes
    #  vars:
    #range_home: '10.0.0.0/16'
    #range_hetzner: '10.1.0.0/16'
    #ipadr: '10.0.50.20'
  tasks:
    - name: drop hetzner node 
      ansible.builtin.meta: end_host
      when: "{{ '10.0.0.0/16' | ansible.utils.network_in_network( '10.1.100.10' ) == false and '10.0.0.0/16' | ansible.utils.network_in_network( ansible_host ) == false}}"

    - name: debug 
      ansible.builtin.debug:
        msg: "{{ '10.0.0.0/16' | ansible.utils.network_in_network(ansible_host) }}"

    - name: drop2 host
      ansible.builtin.meta: end_host
      when: "{{ '10.1.0.0/16' | ansible.utils.network_in_network( '10.1.100.10' ) == false and '10.1.0.0/16' | ansible.utils.network_in_network( ansible_host ) == false}}"
        #    - import_tasks: tasks/create_vm.yml
        
    - name: message
      ansible.builtin.debug:
        msg: ansible_host 
