- name: add overlay module
  community.general.modprobe:
    name: overlay
    state: present
    persistent: present

- name: add br_netfilter module
  community.general.modprobe:
    name: br_netfilter
    state: present
    persistent: present

- name: net.bridge.bridge-nf-call-iptables = 1 to sysctl 
  ansible.posix.sysctl:
    name: net.bridge.bridge-nf-call-iptables
    value: 1
    state: present
    sysctl_file: /etc/sysctl.d/k8s.conf

- name: net.bridge.bridge-nf-call-ip6tables = 1 to sysctl
  ansible.posix.sysctl:
    name: net.bridge.bridge-nf-call-ip6tables
    value: 1
    state: present
    sysctl_file: /etc/sysctl.d/k8s.conf

- name: net.ipv4.ip_forward = 1 to sysctl
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: 1
    state: present
    sysctl_file: /etc/sysctl.d/k8s.conf

- name: install cri-o key
  ansible.builtin.apt_key:
    url: https://pkgs.k8s.io/addons:/cri-o:/prerelease:/main/deb/Release.key 
    keyring: /etc/apt/keyrings/cri-o-apt-keyring.gpg 
    state: present

- name: install cri-o repository
  ansible.builtin.apt_repository:
    repo: deb [signed-by=/etc/apt/keyrings/cri-o-apt-keyring.gpg] https://pkgs.k8s.io/addons:/cri-o:/prerelease:/main/deb/ / 
    filename: cri-o 

- name: install cri-o
  ansible.builtin.apt:
    pkg:
    - cri-o
    - containernetworking-plugins

- name: hold crio
  ansible.builtin.dpkg_selections:
    name: cri-o
    selection: hold
