- hosts: all 
  become: no
  gather_facts: no
  vars_files:
   - secrets/vault.yml
  tasks:
    # START VM DEPLOY ON LOCALHOST
    - name: start deploy tasks
      include_role:
        name: vm-deploy 
        apply:
          delegate_to: localhost
      when: deploy | default(true) 

    - name: delete inactive VMs
      include_role:
        name: vm-cleanup
        apply:
          delegate_to: localhost
      when: deploy | default(true)

