- hosts: all 
  become: no
  gather_facts: no
  vars_files:
   - secrets/vault.yml
   - vars/vm-lists.yml
  tasks:
    # START VM DEPLOY ON LOCALHOST
    - name: start deploy tasks
      include_role:
        name: vm-deploy 
        apply:
          delegate_to: localhost
      when: deploy | default(true) 

    # START VM DELETION ON LOCALHOST
    - name: delete inactive VMs
      include_role:
        name: vm-cleanup
        apply:
          delegate_to: localhost
      when: deploy | default(true)

    # INSTALL KUBERNETES CORE ON KUBERNETES NODES 
    - name: install kubernetes core
      include_role:
        name: kubernetes-core
      when: kubernetes is defined 
